// Typed API surface — one function per endpoint (v2 contract).

import { request } from './client.js'

export const api = {
  auth: {
    login: (email, password) => request('POST', 'auth/login', { email, password }),
    me: () => request('GET', 'auth/me'),
    updateProfile: (body) => request('PUT', 'auth/profile', body),
    changePassword: (body) => request('POST', 'auth/password', body),
  },
  platform: {
    dashboard: () => request('GET', 'platform/dashboard'),
    revenue: () => request('GET', 'platform/revenue'),
    organisations: (q = '') => request('GET', `platform/organisations${q}`),
    organisation: (id) => request('GET', `platform/organisations/${id}`),
    suspend: (id, reason) => request('POST', `platform/organisations/${id}/suspend`, { reason }),
    ban: (id, reason) => request('POST', `platform/organisations/${id}/ban`, { reason }),
    restore: (id) => request('POST', `platform/organisations/${id}/restore`, {}),
    audit: (q = '') => request('GET', `platform/audit${q}`),
    users: () => request('GET', 'platform/users'),
    createUser: (body) => request('POST', 'platform/users', body),
    updateUser: (id, body) => request('PUT', `platform/users/${id}`, body),
    resetUserPassword: (id) => request('POST', `platform/users/${id}/reset-password`, {}),
    templates: () => request('GET', 'platform/templates'),
    createTemplate: (body) => request('POST', 'platform/templates', body),
    updateTemplate: (id, body) => request('PUT', `platform/templates/${id}`, body),
    deleteTemplate: (id) => request('DELETE', `platform/templates/${id}`),
    generateTemplateAI: (body) => request('POST', 'platform/templates/ai-generate', body),
    frames: () => request('GET', 'platform/frames'),
    createFrame: (body) => request('POST', 'platform/frames', body),
    deleteFrame: (id) => request('DELETE', `platform/frames/${id}`),
  },
  org: {
    dashboard: () => request('GET', 'org/dashboard'),
    revenue: (q = '') => request('GET', `org/revenue${q}`),
    events: (q = '') => request('GET', `org/events${q}`),
    createEvent: (body) => request('POST', 'org/events', body),
    updateEvent: (id, body) => request('PUT', `org/events/${id}`, body),
    pauseEvent: (id) => request('POST', `org/events/${id}/pause`, {}),
    resumeEvent: (id) => request('POST', `org/events/${id}/resume`, {}),
    deleteEvent: (id) => request('DELETE', `org/events/${id}`),
    devices: () => request('GET', 'org/devices'),
    assignDevice: (id, eventId) => request('POST', `org/devices/${id}/assign`, { eventId }),
    unassignDevice: (id) => request('POST', `org/devices/${id}/unassign`, {}),
    removeDevice: (id) => request('DELETE', `org/devices/${id}`),
    tickets: (q = '') => request('GET', `org/tickets${q}`),
    ticket: (id) => request('GET', `org/tickets/${id}`),
    replyTicket: (id, message) => request('POST', `org/tickets/${id}/reply`, { message }),
    resolveTicket: (id, note) => request('POST', `org/tickets/${id}/resolve`, { note }),
    reopenTicket: (id) => request('POST', `org/tickets/${id}/reopen`, {}),
    defaults: () => request('GET', 'org/defaults'),
    saveDefaults: (body) => request('PUT', 'org/defaults', body),
    coupons: () => request('GET', 'org/coupons'),
    createCoupon: (body) => request('POST', 'org/coupons', body),
    updateCoupon: (id, body) => request('PUT', `org/coupons/${id}`, body),
    pauseCoupon: (id) => request('POST', `org/coupons/${id}/pause`, {}),
    activateCoupon: (id) => request('POST', `org/coupons/${id}/activate`, {}),
    deleteCoupon: (id) => request('DELETE', `org/coupons/${id}`),
    team: () => request('GET', 'org/team'),
    createManager: (body) => request('POST', 'org/team', body),
    updateManager: (id, body) => request('PUT', `org/team/${id}`, body),
    deactivateManager: (id) => request('POST', `org/team/${id}/deactivate`, {}),
    activateManager: (id) => request('POST', `org/team/${id}/activate`, {}),
    resetManagerPassword: (id) => request('POST', `org/team/${id}/reset-password`, {}),
    audit: (q = '') => request('GET', `org/audit${q}`),
  },
}
